name: sensors_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus:
  auto_route:
  get_it:
  flutter_reactive_ble:
  permission_handler:
  syncfusion_flutter_charts:
  intl:
  csv:
  path_provider:
  cupertino_icons: ^1.0.2
  wifi_iot:
  wifi_scan:
  is_lock_screen:
  qr_code_scanner:
  mobile_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
